fix: detect if build is running on Docs.rs builder machine
Our Docs.rs builds are failing because SimSIMD's _Float16 type
is not supported on their builder.
```
[INFO] [stderr] warning: simsimd@0.1.0: In file included from rust/lib.c:1:
[INFO] [stderr] warning: simsimd@0.1.0: In file included from include/simsimd/simsimd.h:21:
[INFO] [stderr] warning: simsimd@0.1.0: In file included from include/simsimd/binary.h:23:
[INFO] [stderr] warning: simsimd@0.1.0: include/simsimd/types.h:119:9: error: _Float16 is not supported on this target
[INFO] [stderr] warning: simsimd@0.1.0: typedef _Float16 simsimd_f16_t;
[INFO] [stderr] warning: simsimd@0.1.0:         ^
[INFO] [stderr] warning: simsimd@0.1.0: 1 error generated.
[INFO] [stderr]
[INFO] [stderr] error: failed to run custom build command for `simsimd v0.1.0 (/opt/rustwide/workdir)`
[INFO] [stderr]
[INFO] [stderr] Caused by:
[INFO] [stderr]   process didn't exit successfully: `/opt/rustwide/target/debug/build/simsimd-bf9859d453372522/build-script-build`
```