Fix: Resolving paths
When using `pip install -e .` for local development,
the presence of `packages*` arguments causes name
resolution errors, like:

> AttributeError: module 'simsimd' has no attribute 'pointer_to_sqeuclidean'

Relates to #152